apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: whoami-ping
  namespace: thundercats
  labels:
    app: whoami-ping
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: ping
            image: byrnedo/alpine-curl:0.1.8
            args:
            - http://whoami 